# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: devel
sudo: required
cache: packages

warnings_are_errors: true

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

# for Stan:
before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_github_packages:
  - pbs-software/pbs-data/PBSdata
  - andrewzm/INLA
  - seananderson/sdmTMB
